#!/usr/bin/env bash

function _2fa ()
{
    local cur prev
    _get_comp_words_by_ref -n : cur

    local words=$(cat ~/.2farc | awk -F'=' '{print $1}' | sed 's/_2fa_key//')
    COMPREPLY=($(compgen -W "${words}" -- ${cur}))
    __ltrim_colon_completions "${cur}"
}

complete -F _2fa 2fa

keyName="${1}_2fa_key"
# Create a subshell to prevent keys from being sourced to environment

(
    . "$HOME/.2farc";

    if [[ ! -z "${!keyName}" ]]
    then
        oathtool -b --totp "${!keyName}";
    else
        echo "$0: cannot access '$1': No such 2fa key";
    fi
)
