#!/usr/bin/env bash

shopt -s nullglob globstar

words=$(awk -F'=' '{print $1}' ~/.2farc | sed 's/_2fa_key//')
key=$(printf '%s\n' "${words[@]}" | dmenu "$@")

[[ -n $key ]] || exit
code=$(/home/mbc/.bin/2fa "$key")

echo "$code" | xclip -r -i

