#!/usr/bin/env sh

if [[ "${@}" == *" -h"* ]]; then
	cat<<EOF
Usage: ${0} - [USER@]HOST SESSIONID

Will run userSessionAuthenticate.pl on host with given session id.
EOF
	exit 1
fi

echo "Authorizing session \"${2}\" on ${1}"
ssh ${1} /opt/capmon/utils/userSessionAuthenticate.pl ${2}
