#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'

usage () {
	cat<<EOF
Usage: ${0} - [USER@]HOST SESSIONID

Will run userSessionAuthenticate.pl on host with given session id.
EOF
}

if [[ -z "$@" ]]; then
    usage
    exit 1
fi

if [[ "${@}" == *"-h"* || "${@}" == *"--help"* ]]; then
    usage
    exit 0
fi

host=${1:-}
sessionID=${2:-}

ssh "${host}" /opt/capmon/utils/userSessionAuthenticate.pl \
    "${sessionID}"

echo "Authorizing session \"${sessionID}\" on ${host}"
