#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t' 

HEADER="PRIVATE-TOKEN: glpat-p8SnwyBhV3t43excqg3d"
FROM=''
TO=''
VERSION=''
PROGNAME=$(basename ${0})
usage () {
    cat<<EOF
Usage: ${PROGNAME} [-xh] [-f <from ref>] [-t <to ref>] -v <VERSION>
EOF
}

while getopts 'f:t:v:x' arg; do case $arg in
    f) FROM=${OPTARG};;
    t) TO=${OPTARG};;
    v) VERSION=${OPTARG};;
    x) set -x;;
    h) usage; exit 0;;
    *) echo "invalid option -- '$arg'"; exit 1;;
esac; done

# Remove git@gitlab.capmon.dk,
# Remove .git
# Replace / with %2F for url compatibility
sedstr='s/git@gitlab.capmon.dk://;s/.git$//;s@/@%2F@'
PROJECT=$(git config --get remote.origin.url | sed ${sedstr})

# Remove {"notes":"
# Replace \\n with \n
# Remove "}
jsonsed='s/{"notes":"//;s/\\n/\n/g;s/"}//'
API_URL="https://gitlab.capmon.dk/api/v4/projects/${PROJECT}/repository/changelog?from=${FROM}&to=${TO}&version=${VERSION}"

output=$(curl -s --header "${HEADER}" "${API_URL}")

if [[ "$output" == *'{"error"'* ]]; then
    echo "${PROGNAME}: $output" | sed 's/{"error":"//;s/"}//'
    usage
    exit 1
fi

echo "$output" | sed ${jsonsed}
