#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'

if ! pgrep mpd &>/dev/null ; then
  echo "mpd not running; launching"
  mpd
fi

CMDS=$(cat << 'options'
Toggle playback
Next
Prev
Playlist
Replay
Random
Volume
Enqueue
Play
Clear
options
)
count=$(echo -e "$CMDS" | wc -l)
last_id=""
current=$(mpc current --format ${format})
prompt="Playing: ${current:-nothing}"
cmd="${prompt:0:55}..."

format="\[%position%\] %artist% - %album% - %title%|%file%"

run_dmenu () {
    cat | dmenu -i -l ${count} -p ${cmd}
}

cmd="${1:-$(echo -e "${CMDS}" | run_dmenu)}"
case "${cmd,,}" in
    playlist)
        track=$(mpc playlist --format "${format}" \
            | run_dmenu | grep -oEm 1 '[0-9]*')
        mpc play "${track}" >/dev/null;;
    'toggle playback')
        mpc toggle >/dev/null;;
    next)
        mpc next >/dev/null;;
    prev)
        mpc prev >/dev/null;;
    random)
        mpc random >/dev/null;;
    volume)
        cmd="Volume$(mpc status %volume%):"
        mpc volume $(echo | run_dmenu) >/dev/null;;
    replay)
        mpc play $(mpc current --format %position%);;
    play)
        last_id=$(mpc status "%length%")
        ;&
    add)
        CMDS="Artists\nAlbums\nTitles\nPlaylists"
        cmd="${2:-$(echo -e ${CMDS} | run_dmenu)}"
        case "${cmd,,}" in
            artists)
                artist=$(mpc list artist | run_dmenu)
                mpc findadd artist "${artist}" >/dev/null;;
            albums)
                album=$(mpc list album | run_dmenu)
                mpc findadd album "${album}" >/dev/null;;
            titles)
                title=$(mpc list title | run_dmenu)
                mpc findadd title "${title}" >/dev/null;;
            playlists)
                playlist=$(mpc lsplaylist | run_dmenu)
                mpc load "${playlist}" >/dev/null;;
        esac
        if [[ ! -z "$last_id" ]]; then mpc play $((last_id+1)) >/dev/null; fi;;
    clear)
        mpc clear >/dev/null;;
esac
