#!/usr/bin/env bash

if [ -z "$1" ] || ! [ "$1" -eq "$1" ]
then
    chunks=0
else
    ((chunks=${1}/10))
fi

for ((i=0;i<chunks;++i)); do
    DOTS="${DOTS} ●"
done
if ((${1}-10*chunks > 0)); then
    DOTS="${DOTS} ◉"
    ((++chunks))
fi
for ((i=chunks;i<10;++i)); do
    DOTS="${DOTS} ○"
done
echo "${DOTS}"
