#!/bin/bash

val="$1"
if ! [ "$val" -eq "$val" ] 2>/dev/null
then
    bar="Incorrect usage: expected an integer parameter"
elif [ "$val" = 0 ]
then
    for ((i=0;i<10;++i)); do
        bar="${bar} ○"
    done
else
    bar="   "
    ((chunks=${val}/10))
    for ((i=0;i<chunks;++i)); do
        bar="${bar} ●"
    done
    if (($val-10*chunks > 4)); then
        bar="${bar} ◉"
        ((++chunks))
    fi
    for ((i=chunks;i<10;++i)); do
        bar="${bar} ○"
    done
    #bar="${bar} (${1}%)"
fi
dunstify "$bar" -u low -t 1000 -h int:value:"$val" \
    -h string:synchronous:"$bar" --replace=555 \
    --title "test"
