#!/usr/bin/env sh

while :; do
	host 127-0-0-1.dk > /dev/null 2>&1
	if [ $? -eq 0 ]; then
		env SSH_AUTH_SOCK= ssh -t \
			-o ServerAliveInterval=5 \
			-o ServerAliveCountMax=3 \
			-o ForwardAgent=no \
			-o AddKeysToAgent=no \
			martinmch@127-0-0-1.dk "screen -x pts-5.127-0-0-1"

		if [ X"$?" = X"0" ]; then
			exit
		fi

		# wait until screen is not locked
		sleep 1
    fi
    sleep 2
done
