#!/bin/bash

IMAGE=/tmp/i3lock.png
PLAYING_BEFORE=$(mpc | grep playing)

# Takes a screenshot
IMAGE=$(cat $HOME/.fehbg | grep -o "/home/[^\']*")

if [ ! -z "$PLAYING_BEFORE" ]; then
    mpc pause > /dev/null
fi

i3lock -nui "$IMAGE"

if [ ! -z "$PLAYING_BEFORE" ]; then
    mpc play > /dev/null
fi
