#!/usr/bin/env sh

task=$(_current_task);
if [[ ! -z ${task} ]]
then
	echo "You are not clocked out of ${task}";
	cout
	sleep 5
fi

# Run the system binary for poweroff
$(which --skip-tilde poweroff)
