#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'

# Usage is: ./sign-exe username password

NAME="ResponseView-Setup.exe"
SIGNED_NAME="${NAME%.*}-signed.exe"

trap "popd" EXIT

pushd /tmp/
rm -f "$NAME" "$SIGNED_NAME"
wget download.capmon.dk/"$NAME" --user="$1" --password="$2"

ssh sshcert@sshcert "codesigning" < "$NAME" > "$SIGNED_NAME"

scp "$SIGNED_NAME" root@download.capmon.dk:/srv/web/download/
