#!/usr/bin/env bash

color() { tput sgr0; tput setaf "$1"; cat; tput sgr0; }

red () { color 1; }
green () { color 2; }
yellow () { color 3; }
blue () { color 4; }
purple () { color 5; }

if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    #alias dir='dir --color=auto'
    #alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi
