#!/usr/bin/env sh

SCREEN_WIDTH=`xrandr 2>&1 | grep "Screen 0: minimum" | sed -e 's/.*, current //' -e 's/ x.*//'`
if [ "${SCREEN_WIDTH}" -ge 1920 ]; then
    export HIDPI=1
    export GDK_SCALE=1.5
    export GDK_DPI_SCALE=0.5
    export QT_SCALE_FACTOR=1.1
    export QT_FONT_DPI=96
fi
